#!/bin/sh

default_cmake_keys="-DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RelWithDebugInfo"

check () {
    [[ -f CMakeLists.txt ]]
}

build () {
    mkdir morph_cmake_build
    cd morph_cmake_build
    cmake $default_cmake_keys $cmake_keys ../
    make $make_keys
    make $make_keys $install_keys DESTDIR=$pkgdir install
    cd ..
    rm -rf morph_cmake_build
}
