#!/bin/sh

if [[ -z $python ]]; then
    python=$(which python) &> /dev/null
fi

if ! [[ -f $python ]]; then
    python=$(which $python) &> /dev/null
fi

check () {
    [[ -f setup.py ]] && [[ -f $python ]]
}

build () {
    $python setup.py build
    $python setup.py install --root=$pkgdir --optimize=1
}
