#!/bin/sh

check () {
    [[ -f $(basename ${source_url}) ]]
}

init () {
    proto=$(basename $loader)
    partname=$(basename $source_url).part
    if [[ -f $partname ]]; then
        if ! wget -c $proto:${source_url} -O $partname; then
            rm $partname
            wget $proto:${source_url} -O $partname
        fi
    else
        wget $proto:${source_url} -O $partname
    fi
    mv $partname $(basename $source_url)
}

update () {
    if [[ "$wget_update" ]]; then
        wget -N $(basename $loader):${source_url}
    else
        true
    fi
}
