#!/bin/sh

package () {
    workdir=$(mktemp -d /tmp/morph-mpkg.XXXXXXXX)
    cd $workdir

    cp -R $pkgdir/* .

    mkdir install
    cat > install/data.xml << XML
<?xml version="1.0" encoding="utf-8"?>
<package>
<name>$name</name>
<version>$version</version>
<arch>$arch</arch>
<build>$mbuild</build>
<short_description></short_description>
<dependencies/>
<suggests/>
<maintainer>
	<name>$maintainer_name</name>
	<email>$maintainer_email</email>
</maintainer>
<tags>
XML

    for item in $(echo $tags | tr "," "\n"); do
        echo "<tag>$item</tag>" >> install/data.xml
    done
    echo "</tags></package>" >> install/data.xml

#    info "Generating deps..."
#    mpkg-gendeps2 .

    pkgfile=$package_out_dir/$name-$version-$arch-$mbuild.txz

    info "Creating $pkgfile..."

    [[ "$MORPH_DEBUG" -gt 0 ]] && v=v
    tar cJf$v $pkgfile *

    rm -rf $workdir
    info "$pkgfile created!"
}
